### ISSUE TITLE
need to create an archive of the old schedule

### ISSUE THREAD

**Issue by sinker** [OpenNews/srccon#27]
referenced in #24, we need to create a separate subdomain for the old schedule. @ryanpitts, I leave it to you how best to deal with that (outline some blathery ideas in #24) but once it's ready, let me know and I'll do the CNAME record stuff. Also, we'll then need a placeholder in at schedule.srccon.org

**Comment by sinker** [comment]
repinging @ryanpitts on this. we will need this prior to launch, so we can QA the archive site, which will link to the schedule.

**Comment by ryanpitts** [comment]
Ah, missed this alert first time around. Will make this happen today.

**Comment by ryanpitts** [comment]
I think that in the long run, the simplest, most self-contained way to archive the schedules would be to drop them into a `schedule` directory inside the archived versions of the conference site. Because the schedule is a single-page app and all the static media and session data is packaged right up with it, this shouldn't cause any conflicts.

I think I like this better than going long with the subdomains, a la `schedule2014.srccon.org`, and it also means that we don't end up with double the amount of repos whenever we archive a conference site. And fewer CNAME shenanigans to boot.

Any thoughts @sinker? If this sounds reasonable, I'll drop a `schedule` dir into https://github.com/OpenNews/srccon2014/tree/gh-pages, and update the links within the archived site accordingly.

**Comment by sinker** [comment]
yep, that sounds totally sensible. go for it.

**Comment by ryanpitts** [comment]
ok, done
